AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    test:
        Type: AWS::Serverless::Function
        Properties:
           Handler: listDynamoDB.handler
           Runtime: nodejs6.10
           Timeout: 300
           CodeUri: ./listDynamoDB
           Events:
             HttpPost:
               Type: Api
               Properties:
                 Path: '/AwsSamSpike/test'
                 Method: get
